### ISSUE TITLE
I want to do the same this on REDHAT in aws

### ISSUE THREAD

**Issue by ddiawara** [opendevopsautomation/packer#6]
I have an error with the command gur2-mkconfig

**Comment by vikas-prabhakar** [comment]
1. comment out the rsync step from scripts/lvm_partitions.sh
2. use lvm_partitions.sh to create partition.
3. create a boot directory under mntpoint & mount boot partition, in our case

**Comment by vikas-prabhakar** [comment]
@ddiawara I hope below steps will help you to bake AMI with REDHAt flavour 
1. comment out the rsync step from scripts/lvm_partitions.sh
2. use lvm_partitions.sh to create partition.
3. create a boot directory under mntpoint & mount boot partition, in our case
     mkdir /mnt/boot
     mount /dev/xvdf1 /mnt/boot

4. create a bind mount for the existing root (/) filesystem.
     mkdir /old_root
     mount -o bind / /old_root
5. copy the data on mounted point.
    rsync -avx /old_root/ /mnt/
6. update the fstab file as we overwrite on 5th step.
7. update the grub configuration file for the new disk. Relace GRUB_CMDLINE_LINUX. "rd.lvm.lv=vg_name/lv_name"
    GRUB_CMDLINE_LINUX="crashkernel=auto console=ttyS0,115200 console=tty0 rd.lvm.lv=vol_grp/lv_root"
8. Few steps to create grub file. The errors about lvmetad can be ignored.
     mount -o bind /dev /mnt/dev
     mount -o bind /sys /mnt/sys
     mount -o bind /proc /mnt/proc
     chroot /mnt/
     grub2-mkconfig -o /boot/grub2/grub.cfg.  #note down the output of this step as it will require in next step . Similar to "Found initrd image: /boot/initramfs-***********.x86_64.img"
9. create a new initramfs file
    dracut -f -v /boot/initramfs-***********.x86_64.img
10. Install grub to boot sector of attached partition
      grub2-install --recheck /dev/xvdf
11. SELinux relabels the copied files when the system boots
     touch /.autorelabel
12. exit & reboot with additional partition.

**Comment by vikas-prabhakar** [comment]
@ddiawara: I am closing this issue, kindly let me know if still you face any issue
